### ISSUE TITLE
The demo site is not accessible in China，What should I do?

### ISSUE THREAD

**Issue by newbigland** [PacktPublishing/Selenium-WebDriver-3-Practical-Guide-Second-Edition#1]
The demo site http://demo-store.seleniumacademy.com is not accessible in China. How do I set up a test site?

**Comment by upgundecha** [comment]
@newbigland I'll check with the hosting provider. Can you help with a screenshot of the error that you see?

**Comment by Tall24** [comment]
Hi there,
The issue was reported 25 days ago, still the site is not accessible. I am in England by the way!!!!

What is wrong, if the author cannot sort out this? I just bought this eBook on last night, to read this weekend!I have also write to publishers.It is not fair!
![demo_store](https://user-images.githubusercontent.com/20837132/45916143-06305e00-be59-11e8-97da-275f8d9a5426.png)

**Comment by upgundecha** [comment]
Hi @Tall24 

The is site is up and running and should be accessible. Do you have any firewall rules added on your router that is blocking the site?

Thanks,
Unmesh

**Comment by ShiMichael** [comment]
this http://magento-demo.lexiconn.com/ works well .THANKS
